version: '3'
services:
  app:
    container_name: "app"
    image: 'node:14.13.1-stretch'
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    working_dir: /myapp
    tty: true
  db:
    container_name: "db"
    image: 'mysql:8'
    ports:
      - "3001:3001"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
